9oormthon-univ-swu/2024_FINAL_STARCAPSULE_FE

- .github/CODEOWNERS
리뷰어 자동 배정을 위하여 CODEOWNERS 파일을 추가하였습니다.
> [개발 환경 설정] 리뷰어 자동 배정 위한 파일 추가

- .eslintrc.js
- craco.config.js
- package-lock.json
- package.json
- src/components/AlertModal.jsx
- src/components/AlertModal.stories.jsx
- src/hooks/useModal.jsx
- 공통으로 사용할 수 있는 모달을 만들었습니다. 
- 개발자의 편의성을 위하여 `useModal()` 훅을 만들었습니다. 이후 모달 컴포넌트 사용시 useModal 훅으로 isOpen, openModal, closeModal을 불러오면 됩니다. 
- storybook으로 문서화 하였습니다.
- lint 설정 중 prop type을 명시하라는 설정이 켜져있어 꺼두었습니다.
- mui 관련 패키지를 설치하였습니다.
- storybook의 플러그인을 하나 설치했습니다. 
- 아직 디자인이 확정된 상태가 아니어서 기능만 만들어두었습니다. 이후 디자인 확정시 리펙토링 예정입니다.
> [공용 컴포넌트] 공통 모달 추가

- src/assets/object_background/default_snowball.svg
- src/assets/object_background/selected_snowball.svg
- src/components/AlertModal.jsx
- src/components/ObjectInSnowball.jsx
- src/components/SelectSnowballObject.jsx
- src/constants/SnowballObjects.js
- src/constants/textStyles.js
- src/constants/theme.js
- src/index.css
- src/storybook/components/Icons.stories.jsx
- src/storybook/components/SelectSnowballObject.stories.jsx
1. 스노우볼 오브젝트 선택하는 버튼을 추가하였습니다.
1. 공용 컴포넌트로 처리하였지만 특정 페이지에서만 사용한다면 해당 폴더로 옮기셔도 됩니다.
> [공용 컴포넌트] 스노우볼 오브젝트 선택하는 버튼 추가

- src/components/SnackBar.jsx
- src/pages/Onboarding/SnowballMake.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/pages/main/Snowball/NavigationButton.jsx
- src/pages/main/Snowball/Snowball.jsx
- src/pages/main/Snowball/SnowballChip.jsx
- src/stores/useAuthStore.js
- src/utils/getFetcher.js
- src/utils/saveTokenFromURL.js
- src/utils/useAxiosWithAuth.js
1. useAxiosWithAuth를 만들어 따로 토큰을 넣거나 ip주소를 갖고오지 않아도 되게 만들었습니다. 
2. useAuthStore를 사용하여 login과 logout, token을 사용하기 쉽게 만들었습니다.
3. 메인페이지 api를 연결하였습니다.
1. useSnackbarStore 만들기 (단순 개발자의 편의를 위한 전역 snackbar 처리. 기존 작성 코드 있음. 얼마 안걸림.)
2. Snackbar 닉네임 수정에 추가하기
> [메인 페이지] API 연결

- package-lock.json
- package.json
- src/index.js
- src/layouts/Layout.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/pages/main/Snowball/LoadingSnowball.jsx
- src/pages/main/Snowball/Snowball.jsx
- src/pages/main/Snowball/SnowballChip.jsx
- src/pages/main/Snowball/SnowballObject.jsx
1. 스노우볼 페이지 전환 시 애니메이션을 추가하였습니다.
1. Loading시 화면 깜빡이는 현상을 제거하였습니다.
3. 눈송이가 여백에도 뜨게 설정하였습니다.
> [메인 페이지] 애니메이션 작업

- src/App.js
- src/components/SnackBar.jsx
- src/pages/Record/GuestForm.jsx
- src/pages/Record/RecordForm.jsx
- src/pages/Record/Test.jsx
- src/pages/Record/components/RecordTitle.jsx
- src/pages/guest/Guest.jsx
- src/pages/main/Main.jsx
- src/stores/useNicknameStore.js
- src/stores/useUserStore.js
> 본인기록의 제목을 수정하는 부분에서 발생하는 오류 2가지 해결
1. 질문API가 적용된 타이틀이 수정하지 않고 저장한다면, title 데이터가 null 인 상태로 전달되지 않는 문제 해결
2. 타이틀 수정이 이루어지지 않는 문제 해결
<br>
> 스노우볼 생성자의 닉네임을 타인기록에서 가져와 연결
1. guest 접근 시, 스노우볼 생성자의 닉네임 저장하는 전역 상태 파일 추가
2. 이후 guest 컴포넌트에서 데이터(닉네임)을 가져오는 get fetcher 함수 추가
<br>
> API연동 현재 상황
1. 현재 개인기록 및 타인기록 모두 동일한 500에러가 발생하고 있습니다. (+백엔드와 해결한 영역)
(백엔드)정은님께서 두 기록간의 오브젝트가 반대인 상태로 현재는 DB 수정한 상태 <br>==> 제가 BE 수정할 때 바로 연동이 되는건지 모르겠어서, 아직까지도 해결이 안되는 부분 중 하나입니다. <br>
<hr>
1. (수정 사항)  스낵바 위치를 살짝 위쪽으로 조정하였습니다. 
3. (진행 사항)  이미지업로드 버튼 개선중입니다. 
_다회성으로_ 이미지를 바꾸는 건 가능한데 이미지 파일이 서버로 전달하지 못한 문제가 발생해서 <br>_현재 PR은 기존 파일로 대체합니다._
> [기록 작성] 타인기록 닉네임 연결 추가 및 타이틀 오류 수정

- src/App.js
- src/pages/Onboarding/PopupButton.jsx
- src/pages/Record/RecordFormAfter.jsx
- src/pages/Record/components/RecordSaveButton.jsx
1. 별거는 아니고 파일 생성 후 컴포넌트만 옮겨왔습니다!
> [12/31기록확인] 화면

- src/utils/getDaysBeforeOpen.js
1. 플러그인 추가해야했는데 깜빡했습니다... 그부분 추가했습니다.
+ 추가적으로 애니메이션 관련 경고가 계속 뜨고있는데 그부분 시험 끝나고 해결하겠습니다. (Iconbutton2관련해서도요)
> [메인페이지] isBetween 플러그인 빠진 것 해결

- src/pages/main/Calendar/Calendar.jsx
- src/pages/main/Calendar/Day.jsx
- src/pages/main/CalendarPage.jsx
2025년도에도 2024년도 데이터 확인할 수 있도록 처리하였습니다.
주석은 2025년 작업자를 위해 남겨주세요
> [캘린더 페이지] api와 내후년 서비스를 고려한 리펙토링

- src/App.jsx
- src/components/SnackbarNoti.jsx
- src/layouts/Layout.jsx
- src/pages/Onboarding/PopupAfter.jsx
- src/pages/Record/GuestForm.jsx
- src/pages/Record/RecordForm.jsx
- src/pages/main/Main.jsx
- src/stores/useSnackbarStore.js
- src/stores/useToastStore.js
- src/utils/useAxiosWithAuth.js
1. 스낵바 알림을 전역 처리하였습니다. 관련한 문서는 #67 에서 보실 수 있습니다. 
2. Layout 컴포넌트를 기준으로 페이지 전환 애니메이션을 추가하였습니다. 혹시나 적용 안된 페이지가 있다면 적용 부탁드립니다! 
1. 페이지 전환 애니메이션을 적용하며 전체 화면을 덮는 overlay가 깨지는 현상이 있었습니다. mui Portal 컴포넌트를 이용하여 해결해두었으니, 다른 페이지에서 적용이 안된다면 해당 컴포넌트를 활용하는 것을 추천드립니다. 
close: #66, #37
> [공용 컴포넌트] 스낵바 알림 전역 처리 및 페이지 전환 애니메이션 추가

- src/pages/RecordComplete/CalendarDetail.jsx
- src/pages/main/Calendar/Day.jsx
특정 날짜를 클릭하면 기록이 보이도록 구현 했습니다
기록이 여러개일 경우 < > 버튼을 통해 넘길 수 있습니다.
css 부분 수정 필요합니다
> [달력 기록확인] 달력 특정 날짜 조회 데이터 연결

- src/constants/theme.js
- src/pages/Onboarding/SnowballMake.jsx
- src/pages/Record/RecordForm.jsx
- src/pages/RecordComplete/CalendarDetail.jsx
- src/pages/RecordComplete/CreationComplete.jsx
- src/pages/RecordComplete/GuestFormAfter.jsx
- src/pages/RecordComplete/MyCreationComplete.jsx
- src/pages/RecordComplete/RecordFormAfter.jsx
- src/pages/guest/Guest.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/pages/main/Snowball/NavigationButton.jsx
- src/pages/main/Snowball/Snowball.jsx
- src/pages/main/Snowball/SnowballObject.jsx
- src/stores/useAuthStore.js
- src/utils/useAxiosWithAuth.js
1. 기존에 있던 위치를 기억하지 못하는 현상을 수정하였습니다.
2. 닉네임 수정 취소 로직을 추가하였습니다.
머지를 먼저 하고 작업에 들어가야 했는데 develop에서 풀만 받고 머지를 안했더라고요... 혹시 충돌로 인해 사라진 코드가 있다면 알려주시기 바랍니다.
> [메인 페이지] 페이지네이션 개선

- .gitignore
- src/main.jsx
- src/pages/Onboarding/LoginPage.jsx
- src/pages/main/Main.jsx
- src/stores/useAuthStore.js
1. 로그아웃 시 로컬스토리지를 모두 지우도록 처리했습니다.
2. 로컬스토리지에 토큰과 userid가 있다면 메인으로 넘어가도록 처리하였습니다.
> [로그아웃 로직] 로그아웃 로직 수정

- src/stores/useAuthStore.js
- src/utils/saveTokenFromURL.js
- src/utils/useAxiosWithAuth.js
1. 로그인 시 토큰이 저장 안되던 문제를 해결하였습니다... 언제 로그인 코드에 로컬스토리지 관련이 날아간지 모르겠네요...
> [로그인] 로컬스토리지에 토큰 저장 안되던 문제

- src/pages/Onboarding/LoginPage.jsx
로그인 페이지에서 api 요청을 환경변수로 처리되지 않은 부분을 고쳤습니다.
> [로그인 페이지] api 요청 위치 환경변수로 변환

- src/App.jsx
- src/pages/Onboarding/LoginPage.jsx
- src/pages/Onboarding/PopupPage.jsx
- src/pages/calendar/Calendar.jsx
- src/pages/calendar/Day.jsx
- src/pages/guest/Guest.jsx
- src/pages/main/DDayTitle.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/utils/getDaysBeforeOpen.js
- src/utils/isRecordable.js
1. 날짜를 잘못 가져오던 현상을 수정하였습니다.
2. 이제 환경변수를 기준으로 기록가능여부를 판단합니다.
> [메인, 캘린더 페이지] 날짜 잘못 가져오던 현상

- index.html
- src/pages/guest/Guest.jsx
1. 기록 작성 페이지로 안넘어가는 현상을 수정하였습니다.
2. description이 기본 값으로 뜨는 현상을 수정하였습니다.
> [게스트페이지] 기록 작성 페이지로 안넘어가는 현상

- src/pages/Onboarding/SnowballMake.jsx
- src/pages/calendar/Day.jsx
- src/pages/main/Main.jsx
- 배경 이미지 안뜨던거 수정
- 달력 클릭 시 기록 못보도록 막음
> Feat: 배경 및 기능 수정

- src/pages/error/ErrorBoundary.jsx
ErrorBoundary에서 500번 이상의 에러만 잡도록 수정하였습니다.
> [에러페이지] ErrorBoundary 수정

- src/pages/calendar/Calendar.jsx
- src/pages/calendar/CalendarPage.jsx
- src/pages/calendar/Day.jsx
- src/pages/main/Main.jsx
1. 캘린더 이상한 ui 수정 #115 
2. 메인 페이지 기록 작성 버튼 활성화 안되는 현상 수정
close: #115
> [메인, 캘린더 페이지] #115번 수정, 메인페이지 기록 작성 버튼 활성화 안되는 현상 수정

- src/pages/calendar/CalendarPage.jsx
- src/pages/main/Main.jsx
- src/stores/useUserStore.js
잘못된 uid 값이라도 저장되어버리는 현상을 수정하였습니다.
> [메인페이지] 잘못된 uid 저장하는 현상 수정

- package-lock.json
- src/firebase-message-sw.js
- src/pages/Onboarding/LoginPage.jsx
- src/pages/Record/GuestForm.jsx
- src/pages/Record/components/RecordBoard.jsx
- src/pages/Record/components/RecordTitle.jsx
- src/pages/RecordComplete/CreationComplete.jsx
- src/pages/RecordComplete/RecordFormAfter.jsx
- src/pages/main/Main.jsx
카톡에 올라온 토스트 에러 해결 및 그 외 자잘한 기타 수정
> [메인페이지] 토스트에러 해결

- src/pages/main/Main.jsx
- src/pages/main/Snowball/NavigationButton.jsx
- src/pages/main/guest/Guest.jsx
1. 워딩 잘못된 것 수정
2. 화살표 그림자 추가
3. 다음페이지로 안가는 버그 수정
> [메인페이지] 자잘한 버그 수정

- src/App.jsx
- src/pages/RecordComplete/CreationComplete.jsx
- src/pages/RecordComplete/MyCreationComplete.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/pages/main/guest/Guest.jsx
- src/utils/isPWAInstalled.js
1. 사용자 유도 모달을 띄울 수 있도록 처리했습니다.
1. 닉네임 수정 완료 후 취소 로직을 불러오는 현상을 수정하였습니다.
> [메인페이지] 사용자 유도 모달 적용 완료

- src/components/AlertModal.jsx
- src/components/ShareModal.jsx
- src/pages/Record/components/RecordUpper.jsx
- src/pages/RecordComplete/CalendarDetail.jsx
- src/pages/RecordComplete/GuestFormAfter.jsx
- src/pages/RecordComplete/RecordFormAfter.jsx
1. CloseIcon에 색상 적용이 안된 것들을 수정하였습니다. 
내일 전체적으로 색상이 바뀐 것 적용하고 올리려 했는데, 색상이 일괄로 변경이 되는 상황이 아니라고 하셔서 이것만 올립니다.
> [전체] closeIcon 색상적용 안된 것 수정

- package-lock.json
- package.json
- src/pages/Onboarding/SnowballMake.jsx
- src/pages/main/Main.jsx
- src/pages/main/MainTitle.jsx
- src/utils/isGuestObjects.js
- src/utils/saveTokenFromURL.js
1. 타인 기록은 바로 열리도록 처리하였습니다.
1. 최초 로그인 시 이장한 페이지로 가는 현상을 수정하였습니다.
3. 터치 이벤트 안받는 현상 수정하였습니다
> [메인 페이지] 자잘한 오류 수정

- index.html
- public/pwabuilder-sw.js
- src/main.jsx
- src/pages/Onboarding/SnowballMake.jsx
- src/pages/main/Main.jsx
1. PWA 자동 업데이트 기능을 추가하였습니다. 
1. PWA 팝업이 자동으로 안열리는 현상을 해결하였습니다.
2. 바뀐 테마 색상을 적용하였습니다.
3. 스노우볼 생성 시 이상한 곳으로 가는 현상을 수정하였습니다.
> [PWA] PWA 자동 업데이트

- public/pwabuilder-sw.js
- src/App.jsx
- src/pages/error/InAppBrowserBlocker.jsx
1. pwa에서 오류내던 것을 수정하였습니다.
2. 인앱브라우저 리다이렉션 위치 지정했습니다.
> [인앱브라우저] 리다이렉션 링크 지정

- src/pages/main/MainPage.jsx
1. 로그인 당시가 아닌 상황에서도 userId가 수정되는 현상
2. 로그인 안하면 아무것도 안보여지는 현상
> [메인 페이지] 게스트 페이지가 아무것도 안보이는 현상

- public/service-worker.js
- src/components/SelectSnowballObject.jsx
- src/pages/Record/GuestForm.jsx
> [게스트 폼] 자동으로 /로 가는 현상

- src/App.jsx
> [게스트 페이지] 게스트 페이지 다시 추가

- src/App.jsx
- src/pages/Record/GuestForm.jsx
> [게스트 작성폼] api base url 빠진 것 수정

- src/pages/Record/GuestForm.jsx
- src/pages/Record/RecordForm.jsx
- src/pages/main/Main.jsx
개인기록 타인기록 모두 api 요청하는 과정에서 여러번 제출하지 않도록 코드를 수정하였습니다.
> [기록작성] 기록제출 시 여러번 눌리지 않게 방지하는 코드 추가

- src/pages/Record/components/RecordSaveButton.jsx
- src/pages/error/InAppBrowserBlocker.jsx
로컬에서는 보기 힘들어서 배포 푸에 시스템에서 뜰 수 있는 지 확인하기 위한 작업을 진행했습니다.
> [인앱브라우저] 시스템에서 열기가 뜨도록 하기 1차 확인용

- src/pages/Onboarding/SnowballMake.jsx
> [초기 로그인] 초기 로그인 시 게스트 페이지로 가는 현상

- src/pages/main/guest/GoToMineTag.jsx
- src/pages/main/guest/Guest.jsx
> [게스트페이지] 내 스노우볼로 이동하기 버튼 추가

- index.html
- src/pages/Onboarding/LoginPage.jsx
- src/pages/main/Main.jsx
1. 이유를 모르겠지만 메타태그 테스터에서 이미지가 안보여서 다시 처리하였습니다.
> [SEO 최적화] 공용 태그와 아닌 것 분리 

- src/pages/main/Main.jsx
- src/pages/main/guest/Guest.jsx
1. 팀 소개 버튼이 작동하지 않는 현상을 수정하였습니다.
> [메인, 게스트 페이지] 팀소개 버튼 작동 안하는 현상
